#!/usr/bin/php
<?php
/* for backlog item's NOT done and NOT in current Sprint
		- 'pre-test uitvoeren' verwijderen
		- 'STD schrijven' => + 'pre-test doen' + 'SDD reviewen'
		- 'STD review verwerken' => + 'pre-test draaien'
 */

require_once 'Scrumwise/Scrumwise.php';

$p = Scrumwise::getProject();

$da = $p->getTag('Deellevering-A');
$db = $p->getTag('Deellevering-B');
$dc = $p->getTag('Deellevering-C');
$dd = $p->getTag('Deellevering-D');

foreach($p->releases as $release) {
	switch(substr($release->name, -3)) {
	case '(A)': $d = $da; break;
	case '(B)': $d = $db; break;
	case '(C)': $d = $dc; break;
	case '(D)': $d = $dd; break;
	default:	$d = NULL;
	}

	if(is_null($d))
		continue;

	echo $release->name." -- ".$d->name."\n";


	foreach($p->getBacklogItemsByRelease($release) as $bl) {
		echo " ".$bl->name."\n";

		if($da != $d && $bl->hasTag($da)) $bl->untag($da);
		if($db != $d && $bl->hasTag($db)) $bl->untag($db);
		if($dc != $d && $bl->hasTag($dc)) $bl->untag($dc);
		if($dd != $d && $bl->hasTag($dd)) $bl->untag($dd);

		if(!$bl->hasTag($d)) $bl->tag($d);
	}
}
