#!/usr/bin/php
<?php
require_once 'Scrumwise/Scrumwise.php';

$p = Scrumwise::getProject();

$tDA = $p->getTag('Deellevering-A');
$tDB = $p->getTag('Deellevering-B');
$tDC = $p->getTag('Deellevering-C');
$tDD = $p->getTag('Deellevering-D');

$sum = [];
foreach($p->backlogItems as $bl) {
	$d = 'Overig';
	if($bl->hasTag($tDA)) $d = 'Deellevering-A';
	if($bl->hasTag($tDB)) $d = 'Deellevering-B';
	if($bl->hasTag($tDC)) $d = 'Deellevering-C';
	if($bl->hasTag($tDD)) $d = 'Deellevering-D';

	@$sum['Totaal']['pts'] += $bl->getEstimate();
	@$sum['Totaal']['cis']++;
	@$sum[$d]['pts'] += $bl->getEstimate();
	@$sum[$d]['cis']++;
}
foreach($sum as $key => $val) {
	printf("%-15s : %3s  %3spts\n", $key, $val['cis'], $val['pts']);
}
