#!/usr/bin/php
<?php
require_once 'Scrumwise/Scrumwise.php';

$p = Scrumwise::getProject();
$tIDD = $p->getTag('IDD');

foreach($p->backlogItems as $b) {
	if(!$b->hasTag($tIDD)) continue;

	echo $b->name . "\n";
	fixIDD($b);
}

function fixIDD($b) {
	if(count($b->tasks) == 0) {
		$b->addTask('Afstemmen met SP team');
		$b->addTask('Rework backlog item(s) aanmaken');
	}
}
