#!/usr/bin/php
<?php
/* List of backlog items that have a mantis reference. */

require_once 'Scrumwise/Scrumwise.php';

$p = Scrumwise::getProject();

$pattern = '/^Mantis3B#(\d+) (.impact: (\w+).)?(.*)$/';

$out = fopen('php://stdout', 'w');
fputcsv($out,
	[ '#sprint', 'status', 'Mantis3B'
	, 'backlogItem', 'impact' #, 'toelichting'
	], ';');

foreach($p->backlogItems as $bl) {

	$sprint = $bl->getSprint();
	if($sprint) $sprint = $sprint->name;

	$status = ($bl->isDone() ? 'done' : 'todo');

	$lines = explode("\n", $bl->description);
	foreach($lines as $line) {
		$matches = [];
		if(!preg_match($pattern, $line, $matches))
			continue;

		$data = [];
		$data[0] = $sprint;
		$data[1] = $status;
		$data[2] = $matches[1];
		$data[3] = $bl->name;
		$data[4] = $matches[3];
#		$data[5] = trim($matches[4]);

		fputcsv($out, $data, ';');
	}
}
