#!/usr/bin/php
<?php
/* List of backlog items that have a mantis reference. */

require_once 'Scrumwise/Scrumwise.php';

$p = Scrumwise::getProject();

$pattern = '/^Mantis3B#(\d+) (.impact: (\w+).)?(.*)$/';

$out = fopen('php://stdout', 'w');
fputcsv($out, [ '#backlogItem', 'Mantis3B', 'impact', 'toelichting' ], ';');

foreach($p->backlogItems as $bl) {
	if($bl->isDone())
		continue;

	$lines = explode("\n", $bl->description);
	foreach($lines as $line) {
		$matches = [];
		if(!preg_match($pattern, $line, $matches))
			continue;

		$matches[0] = $bl->name;
		$matches[2] = $matches[3];
		$matches[3] = trim($matches[4]);
		unset($matches[4]);

		fputcsv($out, $matches, ';');
	}
}
