#!/usr/bin/php
<?php
require_once 'Scrumwise/Scrumwise.php';

$p = Scrumwise::getProject();

$IT  = $p->getTag('IT');
$SIM = $p->getTag('SIM');
$SP  = $p->getTag('SP');

$VKF1 = $p->getTag('VKF1');
$VKF2 = $p->getTag('VKF2');
$VKF3 = $p->getTag('VKF3');
$CAL  = $p->getTag('!C');
$BB12 = $p->getTag('BB-2012');
$OVER = $p->getTag('Overig');

$PRIOS = [ $VKF1, $VKF2, $VKF3, $CAL, $BB12, $OVER ];

$total[0] = 0;
$total['Total'] = 0;
$total['Done']  = 0;
$total['Todo']  = 0;
$total['ToDo-Module'] = 0;
$total['ToDo-Cluster'] = 0;
$total['ToDo-SP'] = 0;

$out = fopen('php://stdout', 'w');
fputcsv($out, [ "#release", "prio" ] + array_keys($total), ';');

foreach($p->releases as $release)
{
	foreach($PRIOS as $PRIO)
	{
		$stats = [];
		foreach($total as $key => $val)
			$stats[$key] = 0;

		$print = false;

		foreach($p->getBacklogItemsByRelease($release) as $backlogItem)
		{
			if(!$backlogItem->hasTag($PRIO)
			|| $backlogItem->hasTag($IT))
				continue;

			$print = true;

			$pts = $backlogItem->getEstimate();
			if($pts < 0) $pts = 0;

			$stats['Total'] += $pts;

			if($backlogItem->isDone()) {
				$stats['Done'] += $pts;
				continue;
			}
			$stats['Todo'] += $pts;

			if($backlogItem->hasTag($SP)) {
				$stats['ToDo-SP'] += $pts;
				continue;
			}
			if($backlogItem->hasTag($SIM)
			|| strpos($backlogItem->name, 'Cluster') !== FALSE
			|| strpos($backlogItem->name, 'Applicatie') !== FALSE) {
				$stats['ToDo-Cluster'] += $pts;
				continue;
			}

			$stats['ToDo-Module'] += $pts;
		}
		if(!$print) continue;
		fputcsv($out, [ $release->name, $PRIO->name ] + $stats, ';');
	}
}
fclose($out);
