#!/usr/bin/php
<?php
require_once 'Scrumwise/Scrumwise.php';

$p = Scrumwise::getProject();
$IT  = $p->getTag('IT');
$SIM = $p->getTag('SIM');
$SP  = $p->getTag('SP');

$total[0] = 0;
$total['Total'] = 0;
$total['Done']  = 0;
$total['Todo']  = 0;
$total['ToDo-Module'] = 0;
$total['ToDo-Cluster'] = 0;
$total['ToDo-SP'] = 0;

$out = fopen('php://stdout', 'w');
fputcsv($out, [ "#release" ] + array_keys($total), ';');

foreach($p->releases as $release)
{
	$stats = [];
	foreach($total as $key => $val)
		$stats[$key] = 0;

	foreach($p->getBacklogItemsByRelease($release) as $backlogItem)
	{
		if($backlogItem->hasTag($IT))
			continue;

		$pts = $backlogItem->getEstimate();
		if($pts < 0) $pts = 0;

		$stats['Total'] += $pts;

		if($backlogItem->isDone()) {
			$stats['Done'] += $pts;
			continue;
		}
		$stats['Todo'] += $pts;

		if($backlogItem->hasTag($SP)) {
			$stats['ToDo-SP'] += $pts;
			continue;
		}
		if($backlogItem->hasTag($SIM)
		|| strpos($backlogItem->name, 'Cluster') !== FALSE
		|| strpos($backlogItem->name, 'Applicatie') !== FALSE) {
			$stats['ToDo-Cluster'] += $pts;
			continue;
		}

		$stats['ToDo-Module'] += $pts;
	}
	fputcsv($out, [ $release->name ] + $stats, ';');

	foreach($stats as $key => $val)
		$total[$key] += $val;
}

fputcsv($out, [ "Total" ] + $total, ';');
fclose($out);
