#!/usr/bin/php
<?php
require_once 'Scrumwise/Scrumwise.php';

Scrumwise::updateCache(getenv('SCRUMWISE_UPDATE'));
$p = Scrumwise::getProject();
$REWORK = $p->getTag('REWORK');
$IT = $p->getTag('IT');

$total[0] = 0;
$total['Total'] = 0;
$total['Done']  = 0;
$total['Todo']  = 0;
$total['Rework-Done'] = 0;
$total['Rework-Todo'] = 0;

$out = fopen('php://stdout', 'w');
fputcsv($out, [ "#release" ] + array_keys($total), ';');

foreach($p->releases as $release)
{
	$stats = [];
	foreach($total as $key => $val)
		$stats[$key] = 0;

	foreach($p->getBacklogItemsByRelease($release) as $backlogItem)
	{
		if($backlogItem->hasTag($IT)) continue;

		$isRework = $backlogItem->hasTag($REWORK);
		$pts = $backlogItem->getEstimate();
		if($pts < 0) $pts = 0;

		$stats['Total'] += $pts;

		switch($backlogItem->status) {
		case 'Done':
		case 'Sprint completed':
		case 'Released':
			$stats['Done'] += $pts;
			if($isRework)
				$stats['Rework-Done'] += $pts;
			break;
		default:
			$stats['Todo'] += $pts;
			if($isRework)
				$stats['Rework-Todo'] += $pts;
		}
	}
	fputcsv($out, [ $release->name ] + $stats, ';');

	foreach($stats as $key => $val)
		$total[$key] += $val;
}

fputcsv($out, [ "Total" ] + $total, ';');
fclose($out);
